matrix:
  include:
  - os: osx
    osx_image: xcode9.4
    language: node_js
    node_js: '10'
    env:
    - CSC_KEYCHAIN=login
    - CSC_LINK=.webitel.p12
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
  - os: linux
    sudo: required
    services: docker
    language: generic
cache:
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
addons:
  ssh_known_hosts: cloud-ams1.webitel.com
before_cache:
- rm -rf $HOME/.cache/electron-builder
before_install:
- openssl aes-256-cbc -K $encrypted_e7b490a66fed_key -iv $encrypted_e7b490a66fed_iv
  -in id_rsa.enc -out id_rsa -d
- chmod +x ci-build.sh
script: "./ci-build.sh"
after_success:
  - bash ci-publish.sh
